# Generated by Django 4.2.3 on 2023-08-04 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_post/', verbose_name='Видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_qty', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.post', verbose_name='Автор')),
            ],
        ),
    ]
