# Generated by Django 4.2.3 on 2023-08-07 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_short_options_post_likes_savedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='short',
            name='video',
            field=models.FileField(null=True, upload_to='video_post/', verbose_name='Видео'),
        ),
    ]
