# Generated by Django 4.2.3 on 2023-08-14 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_comment_created_by_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriber',
            field=models.ManyToManyField(null=True, related_name='subscribed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_post/', verbose_name='Фотография'),
        ),
    ]
