# Generated by Django 4.2.3 on 2023-08-15 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_profile_subscriber_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriber',
            field=models.ManyToManyField(related_name='followed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
