# Generated by Django 4.2.3 on 2023-08-15 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_profile_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='followed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
